"""
Database Seeding Script for AgentCare (Type-2 Diabetes Management Support).

SAFETY NOTICE:
AgentCare is an AI clinical decision support system designed to assist clinicians and patients.
It DOES NOT diagnose medical conditions or prescribe medications.
All data generated by this script is strictly synthetic demo data for Type-2 Diabetes management.
No real patient or clinical data is included.
"""

import sys
import os
from datetime import datetime, timedelta, timezone
from passlib.hash import pbkdf2_sha256

# Add backend directory to Python module search path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.db.database import engine, Base, SessionLocal
from app.models.user import User, PatientProfile
from app.models.diabetes_record import DiabetesRecord
from app.models.medication import Medication
from app.models.reminder import Reminder


def seed_database():
    print("🌱 Initializing AgentCare database tables...")
    # Re-create all tables for a clean seed environment
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()

    try:
        print("👤 Seeding Clinician and Patient users...")
        
        # 1. Clinician User
        clinician_user = User(
            username="dr_jenkins",
            password_hash=pbkdf2_sha256.hash("clinician123"),
            role="clinician",
            full_name="Dr. Sarah Jenkins, MD",
        )
        db.add(clinician_user)

        # 2. Patient User
        patient_user = User(
            username="john_doe",
            password_hash=pbkdf2_sha256.hash("patient123"),
            role="patient",
            full_name="John Doe",
        )
        db.add(patient_user)
        db.commit()
        db.refresh(patient_user)

        # 3. Patient Profile for Type-2 Diabetes management
        print("📋 Seeding Patient Profile for Type-2 Diabetes management...")
        patient_profile = PatientProfile(
            user_id=patient_user.id,
            age=54,
            gender="Male",
            diabetes_duration_years=4.5,  # Living with Type-2 Diabetes for 4.5 years
            target_hba1c=7.0,              # Target HbA1c goal (%)
        )
        db.add(patient_profile)
        db.commit()
        db.refresh(patient_profile)

        now = datetime.now(timezone.utc).replace(tzinfo=None)

        # 4. Synthetic Diabetes Records
        print("📊 Seeding synthetic Type-2 Diabetes records (HbA1c, glucose readings, history, lifestyle)...")
        records = [
            # HbA1c Lab Reading
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="hba1c",
                value=7.5,
                unit="%",
                date=now - timedelta(days=3),
                notes="Quarterly HbA1c lab test for Type-2 Diabetes evaluation. Target is 7.0%.",
                raw_text="Lab Result - HbA1c: 7.5%. Patient shows moderate glycemic control over past 3 months.",
            ),
            # Fasting & Postprandial Blood Glucose Readings
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="blood_glucose",
                value=135.0,
                unit="mg/dL",
                date=now - timedelta(days=2, hours=14),
                notes="Morning fasting blood glucose reading.",
                raw_text="Self-monitored blood glucose: 135 mg/dL (Fasting).",
            ),
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="blood_glucose",
                value=165.0,
                unit="mg/dL",
                date=now - timedelta(days=2, hours=6),
                notes="2-hour post-lunch blood glucose reading.",
                raw_text="Self-monitored blood glucose: 165 mg/dL (Postprandial).",
            ),
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="blood_glucose",
                value=128.0,
                unit="mg/dL",
                date=now - timedelta(days=1, hours=14),
                notes="Morning fasting blood glucose reading.",
                raw_text="Self-monitored blood glucose: 128 mg/dL (Fasting).",
            ),
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="blood_glucose",
                value=158.0,
                unit="mg/dL",
                date=now - timedelta(days=1, hours=4),
                notes="2-hour post-dinner blood glucose reading.",
                raw_text="Self-monitored blood glucose: 158 mg/dL (Postprandial).",
            ),
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="blood_glucose",
                value=132.0,
                unit="mg/dL",
                date=now - timedelta(hours=3),
                notes="Today's morning fasting blood glucose reading.",
                raw_text="Self-monitored blood glucose: 132 mg/dL (Fasting).",
            ),
            # Clinical History Summary Note
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="history",
                value=None,
                unit=None,
                date=now - timedelta(days=30),
                notes="Longitudinal Type-2 Diabetes History: Patient diagnosed 2021. Managed via oral biguanide (Metformin) and routine dietary adjustments. No retinopathy or nephropathy detected.",
                raw_text="Clinical Encounter Summary: 54yo male with 4.5yr history of Type-2 Diabetes Mellitus. Patient maintains good medication adherence. Reports mild fatigue during high-carbohydrate meals.",
            ),
            # Lifestyle Record
            DiabetesRecord(
                patient_id=patient_profile.id,
                record_type="lifestyle",
                value=None,
                unit=None,
                date=now - timedelta(days=5),
                notes="Physical Activity & Nutrition: Walks 30 minutes 4 days/week. Aiming for consistent carbohydrate distribution across meals.",
                raw_text="Patient self-report: Exercise routine maintained. Working on reducing sugary drinks.",
            ),
        ]
        db.add_all(records)

        # 5. Synthetic Prescribed Medication
        print("💊 Seeding synthetic prescription records (Metformin 500mg)...")
        medication = Medication(
            patient_id=patient_profile.id,
            name="Metformin",
            dosage="500mg",
            frequency="Twice daily with meals (morning & evening)",
            start_date=now - timedelta(days=180),
            end_date=None,  # Ongoing prescription
            prescribing_doctor="Dr. Sarah Jenkins, MD",
        )
        db.add(medication)

        # 6. Synthetic Reminders
        print("⏰ Seeding Type-2 Diabetes reminders (medications, blood glucose checks, appointments)...")
        reminders = [
            Reminder(
                patient_id=patient_profile.id,
                reminder_type="glucose_check",
                message="Fasting Blood Glucose Check — Log your morning blood glucose reading before breakfast.",
                scheduled_time=now + timedelta(hours=10),
                is_completed=False,
            ),
            Reminder(
                patient_id=patient_profile.id,
                reminder_type="medication",
                message="Take Metformin 500mg — Take 1 tablet with morning breakfast.",
                scheduled_time=now + timedelta(hours=10, minutes=30),
                is_completed=False,
            ),
            Reminder(
                patient_id=patient_profile.id,
                reminder_type="medication",
                message="Take Metformin 500mg — Take 1 tablet with evening dinner.",
                scheduled_time=now + timedelta(hours=20),
                is_completed=False,
            ),
            Reminder(
                patient_id=patient_profile.id,
                reminder_type="lifestyle",
                message="30-Minute Evening Walk — Post-dinner light exercise to assist glycemic regulation.",
                scheduled_time=now + timedelta(hours=21),
                is_completed=False,
            ),
        ]
        db.add_all(reminders)

        db.commit()
        print("✅ Database successfully seeded with synthetic Type-2 Diabetes records!")

    except Exception as e:
        db.rollback()
        print(f"❌ Database seeding failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
